<?php include 'head.php' ?>
<div class='conversation_container'>
	<div class='left_img_col'>
		<div class='profile_img'>
		</div>

	</div>
	<div class='text_col'>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi neque eros, congue quis eros id, consectetur mattis ipsum. Fusce faucibus aliquet diam ut tempus. Donec iaculis dapibus magna, quis dictum turpis luctus eu. Donec eu orci ultricies, lacinia justo quis, varius turpis. Cras at fermentum urna, ac viverra libero. Fusce vehicula ultrices justo vel sodales. Sed euismod libero ut neque egestas elementum id at ligula.
			Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque quam odio, ornare ac orci a, ornare fermentum leo. Maecenas vitae porta massa. Nullam quis tincidunt mi, sed tincidunt lorem. Maecenas fringilla finibus nulla, in pretium magna placerat quis. Cras pulvinar lacus porttitor est maximus fermentum. Ut placerat, lectus et accumsan auctor, turpis urna pharetra erat, id tincidunt magna ligula eget mauris. Morbi ut justo laoreet, pretium magna at, tempor elit. In consequat, nisi eu auctor aliquet, nibh metus semper odio, in volutpat nunc orci venenatis lacus.
			Donec sagittis tristique pellentesque. Nam volutpat est velit, sit amet vulputate eros commodo non. Integer blandit eros ut odio fermentum interdum. Fusce quis ipsum scelerisque, pellentesque elit ut, porta eros. Nam purus turpis, facilisis eget felis ac, convallis tincidunt eros. Sed non diam ac nunc luctus ornare eu sit amet eros. Phasellus nec tellus sit amet nibh volutpat aliquam. Sed blandit imperdiet lorem, id sollicitudin purus elementum ut. Nam hendrerit purus lorem, quis rutrum neque sodales non. Proin id posuere nisl, eget hendrerit tellus.
			Donec bibendum varius purus non viverra. Curabitur vitae ligula diam. Praesent non elit faucibus quam imperdiet feugiat. Sed dignissim laoreet elit, et consectetur mauris commodo et. Ut placerat augue id auctor suscipit. Suspendisse elementum consequat maximus. Sed lobortis eleifend ullamcorper. Nullam commodo purus sed posuere dapibus. Quisque molestie ac sapien ut ultrices. Aenean a tellus vitae velit elementum tempus non vel tortor. Praesent vitae condimentum metus, eget hendrerit arcu. Praesent volutpat commodo purus, scelerisque tempor velit.
			Proin sagittis arcu mauris, in tempor urna tempus et. Aenean et scelerisque lacus. Aenean sit amet auctor dui, ac hendrerit orci. Suspendisse mollis augue congue lacus dapibus, vehicula malesuada nibh pellentesque. Sed justo urna, vestibulum quis malesuada non, mattis sed sem. In id fermentum nisi. Vivamus posuere lectus metus, sit amet semper nunc facilisis et. In eu vulputate mauris. Pellentesque in ante est.
			Praesent a lobortis lectus. Donec ut finibus tellus, in facilisis magna. Sed vel nulla et lacus tristique hendrerit. Donec facilisis elementum dui, eget molestie leo rutrum a. Nunc faucibus sem elit, et molestie dolor egestas a. Praesent justo quam, vulputate id ligula vitae, varius lobortis felis. Etiam iaculis, purus vel aliquam ullamcorper, augue dui mattis est, ut bibendum ligula risus eget massa. Proin augue urna, pulvinar eget tempus a, volutpat ut metus. Sed viverra, ex quis mattis porttitor, quam dolor mollis urna, eget posuere lacus mi vitae dolor. Nam posuere, eros in congue egestas, risus dui feugiat justo, quis ultricies nunc lectus nec est. Donec nec ex orci.
			Aenean rutrum turpis et elit fringilla, accumsan pellentesque lacus tempus. Fusce nec sapien id elit pretium tincidunt. Aliquam dui quam, varius non lacus sed, maximus varius lorem. Sed cursus fermentum dui, eget consectetur massa placerat a. Pellentesque fermentum aliquam lacus vitae vehicula. Maecenas at neque ut nibh fringilla tempor sit amet eu eros. Quisque vestibulum ex eget leo placerat molestie. Sed quis sapien pulvinar sapien consequat blandit eget luctus urna.
			Vivamus molestie odio vestibulum finibus finibus. In hac habitasse platea dictumst. Nam vestibulum diam quis fermentum egestas. Ut tincidunt, nisl ac ullamcorper malesuada, tortor dolor porta nisi, vitae rhoncus purus arcu quis nisi. Duis a augue vitae ligula feugiat interdum. Phasellus volutpat diam nec nisi lobortis dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin aliquam maximus dui nec suscipit. Fusce tristique est est, ac consequat libero congue at. Pellentesque tortor nisi, volutpat vel tempus nec, ultrices a ex. Nunc iaculis mollis cursus. Duis egestas commodo tellus id tristique. Nunc lobortis eros at ornare imperdiet. In ac turpis lectus. Etiam vehicula tellus pretium quam condimentum, quis efficitur elit congue. Aenean pretium feugiat massa nec laoreet.
			Nam ultricies, orci a bibendum rutrum, erat purus rhoncus metus, vitae porttitor risus tortor eget elit. Proin venenatis scelerisque mi, id ullamcorper elit pulvinar sit amet. Nam laoreet leo sit amet justo imperdiet, ut porta eros feugiat. Maecenas sit amet viverra justo, non vestibulum nibh. Vivamus in dictum tellus, id tempus dolor. Suspendisse potenti. Aenean tempor est sem, sit amet mattis metus venenatis id. Aenean lorem nibh, dapibus et pulvinar ultricies, consequat ut ligula. Praesent odio metus, rutrum et urna a, malesuada imperdiet magna. Nam vitae consequat nunc. Nulla sit amet bibendum mi. Phasellus laoreet fermentum velit vel blandit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
			Quisque eu tristique massa. Aenean ultrices, leo nec ullamcorper imperdiet, quam arcu consequat mauris, nec porta elit lacus quis massa. Donec odio tortor, blandit ut suscipit sed, pellentesque id elit. Praesent quis vehicula arcu. Quisque ac justo quis diam porttitor eleifend. Fusce ultricies mi turpis, vitae cursus lorem auctor eu. Maecenas placerat accumsan mauris gravida facilisis. Aenean ut ipsum eros. Maecenas nec varius nulla, sit amet auctor nibh. Maecenas ut est nibh.
		</p>
	</div>
	<div class='right_img_col'>
		<div class='profile_img'>
		</div>
	</div>

</div>	
<?php include 'foot.php' ?>